## 11.2 捕获异常

### 11.2.1 try – except语句

try – except语句的语法如下：

    try：
        <可能会抛出异常的语句>
    Except [异常类型]：
        <处理异常>

1：try代码块  

在try代码块中包含执行过程中可能会抛出异常的语句。

2：except代码块  

每个try代码块可以伴随一个或多个except代码块，用于处理try代码块中所有可能抛出的多种异常。  
except语句如果省略“异常类型”，即不指定具体异常，这样会捕获所有类型的异常；如果指定具体类型异常，则会捕获该类型异常，以及它子类型异常。  

例如：  

    import datetime as dt

    def read_date(in_date):
        try:
            date = dt.datetime.strptime(in_date, '%Y-%m-%d')
            return date
        except ValueError:
            print('处理ValueError异常')

    str_date = '2018-8-18'
    print('日期 = {0}'.format(read_date(str_date)))

    日期 = 2018-08-18 00:00:00

当日期字符串内容被写错时，如下：  

    import datetime as dt

    def read_date(in_date):
        try:
            date = dt.datetime.strptime(in_date, '%Y-%m-%d')
            return date
        except ValueError:
            print('处理ValueError异常')

    str_date = '201B-8-18'
    print('日期 = {0}'.format(read_date(str_date)))

    处理ValueError异常
    日期 = None

由于异常的抛出，执行了except代码块中的内容，当如果不进行捕获时，如下：

    import datetime as dt

    def read_date(in_date):
        # try:
            date = dt.datetime.strptime(in_date, '%Y-%m-%d')
            return date
        # except ValueError:
        #     print('处理ValueError异常')

    str_date = '201B-8-18'
    print('日期 = {0}'.format(read_date(str_date)))

    Traceback (most recent call last):
      File "C:/Users/Marshal/PycharmProjects/study/yichang.py", line 13, in <module>
        print('日期 = {0}'.format(read_date(str_date)))
      File "C:/Users/Marshal/PycharmProjects/study/yichang.py", line 7, in read_date
    date = dt.datetime.strptime(in_date, '%Y-%m-%d')
      File "C:\Users\Marshal\AppData\Local\Programs\Python\Python36-32\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
      File "C:\Users\Marshal\AppData\Local\Programs\Python\Python36-32\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
    ValueError: time data '201B-8-18' does not match format '%Y-%m-%d'

系统平台会报出异常错误。

### 11.2.2 多except代码块

多except代码块语法如下：  

    try：
        <可能会抛出异常的语句>
    Except [异常类型1]：
        <处理异常>
    Except [异常类型2]：
        <处理异常>
    …
    Except [异常类型n]：
        <处理异常>

当捕获的多个异常类之间存在父子关系时，捕获异常顺序与except代码块的顺序有关。从上到下先捕获子类，后捕获父类，否则子类捕获不到。
